from django.urls import path

from .views import (
    AlunoClassroomActivityListView,
    AlunoClassroomDetailView,
    AlunoClassroomGradeListView,
    AlunoClassroomLessonDetailView,
    AlunoClassroomLessonListView,
    AlunoClassroomListView,
    AlunoLessonBlockListView,
    AlunoLessonSectionListView,
    JoinClassroomView,
    ProfessorClassroomActivityListCreateView,
    ProfessorClassroomDetailView,
    ProfessorClassroomGradeListCreateView,
    ProfessorClassroomLessonListCreateView,
    ProfessorClassroomListCreateView,
    ProfessorLessonBlockListCreateView,
    ProfessorLessonSectionListCreateView,
)

urlpatterns = [
    path("classrooms/", ProfessorClassroomListCreateView.as_view(),
         name="classrooms-list-create"),
    path("classrooms/me/", AlunoClassroomListView.as_view(),
         name="classrooms-student-list"),
    path("classrooms/join/", JoinClassroomView.as_view(), name="classrooms-join"),
    path("classrooms/<int:id>/", AlunoClassroomDetailView.as_view(),
         name="classrooms-detail"),
    path("classrooms/professor/<int:id>/",
         ProfessorClassroomDetailView.as_view(), name="classrooms-professor-detail"),
    path("classrooms/<int:id>/activities/",
         ProfessorClassroomActivityListCreateView.as_view(), name="classrooms-professor-activities"),
    path("classrooms/<int:id>/activities/student/",
         AlunoClassroomActivityListView.as_view(), name="classrooms-student-activities"),
    path("classrooms/<int:id>/lessons/",
         ProfessorClassroomLessonListCreateView.as_view(), name="classrooms-professor-lessons"),
    path("classrooms/<int:id>/lessons/<int:lesson_id>/sections/",
         ProfessorLessonSectionListCreateView.as_view(), name="classrooms-professor-sections"),
    path("classrooms/<int:id>/lessons/<int:lesson_id>/sections/<int:section_id>/blocks/",
         ProfessorLessonBlockListCreateView.as_view(), name="classrooms-professor-blocks"),
    path("classrooms/<int:id>/lessons/student/",
         AlunoClassroomLessonListView.as_view(), name="classrooms-student-lessons"),
    path("classrooms/<int:id>/lessons/<int:lesson_id>/sections/student/",
         AlunoLessonSectionListView.as_view(), name="classrooms-student-sections"),
    path("classrooms/<int:id>/lessons/<int:lesson_id>/sections/<int:section_id>/blocks/student/",
         AlunoLessonBlockListView.as_view(), name="classrooms-student-blocks"),
    path("classrooms/<int:id>/lessons/<int:lesson_id>/",
         AlunoClassroomLessonDetailView.as_view(), name="classrooms-student-lesson-detail"),
    path("classrooms/<int:id>/grades/",
         ProfessorClassroomGradeListCreateView.as_view(), name="classrooms-professor-grades"),
    path("classrooms/<int:id>/grades/student/",
         AlunoClassroomGradeListView.as_view(), name="classrooms-student-grades"),
]
