# Generated by Django 6.0.1 on 2026-09-08 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, default='')),
                ('tipo', models.CharField(choices=[('atividade', 'Atividade'), ('trabalho', 'Trabalho'), ('prova', 'Prova'), ('material', 'Material')], default='atividade', max_length=50)),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='turmas.classroom')),
            ],
            options={
                'db_table': 'activities',
                'ordering': ['data_entrega', '-created_at'],
            },
        ),
    ]
