# Generated by Django 6.0.1 on 2026-09-09 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0002_activity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observacao', models.TextField(blank=True, default='')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(limit_choices_to={'role': 'aluno'}, on_delete=django.db.models.deletion.CASCADE, related_name='notas', to=settings.AUTH_USER_MODEL)),
                ('atividade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='turmas.activity')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='turmas.classroom')),
            ],
            options={
                'db_table': 'grades',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('aluno', 'turma', 'atividade'), name='unique_grade_per_student_classroom_activity')],
            },
        ),
    ]
