# Generated by Django 6.0.1 on 2026-09-13 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0003_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, default='')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='turmas.classroom')),
            ],
            options={
                'db_table': 'lessons',
                'ordering': ['ordem', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, default='')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secoes', to='turmas.lesson')),
            ],
            options={
                'db_table': 'lesson_sections',
                'ordering': ['ordem', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('imagem', 'Imagem'), ('video', 'Vídeo'), ('tabela', 'Tabela'), ('lista', 'Lista')], default='texto', max_length=20)),
                ('titulo', models.CharField(blank=True, default='', max_length=255)),
                ('conteudo', models.TextField(blank=True, default='')),
                ('url_imagem', models.URLField(blank=True, default='')),
                ('url_video', models.URLField(blank=True, default='')),
                ('tabela_json', models.JSONField(blank=True, default=dict, null=True)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('secao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocos', to='turmas.lessonsection')),
            ],
            options={
                'db_table': 'lesson_blocks',
                'ordering': ['ordem', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('turma', 'ordem'), name='unique_lesson_order_per_classroom'),
        ),
        migrations.AddConstraint(
            model_name='lessonsection',
            constraint=models.UniqueConstraint(fields=('aula', 'ordem'), name='unique_section_order_per_lesson'),
        ),
        migrations.AddConstraint(
            model_name='lessonblock',
            constraint=models.UniqueConstraint(fields=('secao', 'ordem'), name='unique_block_order_per_section'),
        ),
    ]
